### ISSUE TITLE
Update 180+ count to 200+

### ISSUE THREAD

**Issue by benlk** [INN/inn#106] opened 2019-04-26 15:15 UTC
Raised by @MirandaEcho in today's meeting:
 https://github.com/INN/inn/blob/ae9f2e1563f6c43f99cd4d01033b60f0ca2d6f6b/homepages/templates/inn.php#L41-L53

This 180+ needs to be updated to 200+

**Comment by joshdarby** [comment] 2019-04-26 22:25
@MirandaEcho I will look into this on Monday. Not sure what's going on with the staging site styles. My local looks fine on the same branch. Also, I compared the staging sites css files with my local and they're identical.

**Comment by joshdarby** [comment] 2019-04-29 15:46
Looks like the reason this is being whacky on the staging environment is because of the `WP Event Manager` plugin. If it's active, the buttons inherit some styles from that plugin. If it's disabled, they look fine. Prod and my local both have the plugin disabled, which explains why the issue is not seen on either environment.

**Comment by benlk** [comment] 2019-04-29 15:49
Does the plugin work with those styles dequeued?

**Comment by MirandaEcho** [comment] 2019-04-29 15:51
Or, can we re-sync the staging site so that its back to the older version of the Events Manager Plugin and then make the changes to the numbers?

**Comment by joshdarby** [comment] 2019-04-29 15:51
@benlk I'd think so. Looks like it's the bootstrap file they're loading in that's causing the issues. I'll try dequeuing it.

**Comment by joshdarby** [comment] 2019-04-29 15:58
Actually, we probably don't even have to go that far. They have an option on their settings page to not enqueue Bootstrap on the frontend. 

![Screen Shot 2019-04-29 at 11 57 50 AM](https://user-images.githubusercontent.com/18353636/56909375-23c04880-6a76-11e9-975b-7f7b37519f46.png)

**Comment by joshdarby** [comment] 2019-04-29 17:57
Closing out this issue since the update has been deployed.

**Closed** 2019-04-29 17:57 UTC
Labels: priority: high
